### PR TITLE
FIX Updated dependencies

### PR DESCRIPTION
**Pull request by micmania1**
Addresses #6

### CODE REVIEW

**Comment by tractorcow** [comment]
You'll need to remove master from `.travis.yml`

**Comment by chillu** [comment]
@micmania1 ping

**Comment by tractorcow** [comment]
@micmania1 jpeg

**Comment by dhensby** [comment]
@micmania1 svg

**Comment by tractorcow** [comment]
Sorry svg isn't an allowed_extensions @dhensby

**Comment by dhensby** [comment]
@tractorcow it [is](https://github.com/silverstripe/silverstripe-installer/pull/106) [now](https://github.com/silverstripe/silverstripe-framework/pull/4669)

**Comment by tractorcow** [comment]
Rebase please @micmania1

**Comment by micmania1** [comment]
I don't know why I made this PR but i've rebased. Enjoy.

**Pull request merged**
